wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.30
    code_path: code/main/Decumulate/train_ball_trajectory_depth_jointly_decumulate.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
