wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.30
    code_path: code/main/Jointly/train_ball_trajectory_depth_without_eot_prediction_jointly.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
