#!/bin/bash
DATASET=/home/puntawat/Mint/Work/Vision/BallTrajectory/UnityDataset/
DATASET_CLUSTER=/home2/mint/UnityDataset/RealWorld/
TAGS=Results45@29/09/2020
FORCING= 
# EOT XYZ
python ~/cluster_utils/tasklauncher_uni.py @v2g2 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name BiGRU_eot_xyz --visualization_path ../../visualize_html/test --wandb_notes BiGRU_eot_xyz --model_arch bigru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot && sleep 45 &&
python ~/cluster_utils/tasklauncher_uni.py @v2g3 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name BiLSTM_eot_xyz --visualization_path ../../visualize_html/test --wandb_notes BiLSTM_eot_xyz --model_arch bilstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot && sleep 45 &&
python ~/cluster_utils/tasklauncher_uni.py @v9g0 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name GRU_eot_xyz --visualization_path ../../visualize_html/test --wandb_notes GRU_eot_xyz --model_arch gru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot && sleep 45 &&
python ~/cluster_utils/tasklauncher_uni.py @v9g0 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name LSTM_eot_xyz --visualization_path ../../visualize_html/test --wandb_notes LSTM_eot_xyz --model_arch lstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot && sleep 45 &&
# LATENT XYZ
python ~/cluster_utils/tasklauncher_uni.py @v9g1 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name BiGRU_latent_xyz --visualization_path ../../visualize_html/test --wandb_notes BiGRU_latent_xyz --model_arch bigru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot f_sin f_cos --normalize && sleep 45 &&
python ~/cluster_utils/tasklauncher_uni.py @v9g2 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name BiLSTM_latent_xyz --visualization_path ../../visualize_html/test --wandb_notes BiLSTM_latent_xyz --model_arch bilstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot f_sin f_cos --normalize  && sleep 45 &&
python ~/cluster_utils/tasklauncher_uni.py @v9g3 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name GRU_latent_xyz --visualization_path ../../visualize_html/test --wandb_notes GRU_latent_xyz --model_arch gru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot f_sin f_cos --normalize  && sleep 45 &&
python ~/cluster_utils/tasklauncher_uni.py @v9g3 python train_ball_trajectory_xyz.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags $TAGS  --wandb_name LSTM_latent_xyz --visualization_path ../../visualize_html/test --wandb_notes LSTM_latent_xyz --model_arch lstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ $FORCING --selected_features eot f_sin f_cos --normalize 


