#!/bin/bash
DATASET=/home/puntawat/Mint/Work/Vision/BallTrajectory/UnityDataset/
DATASET_CLUSTER=/home2/mint/UnityDataset/RealWorld/

# EOT DEPTH
python ~/cluster_utils/tasklauncher_uni.py @v1g0 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name BiGRU_eot --visualization_path ../../visualize_html/test --wandb_notes BiGRU_eot --model_arch bigru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot && sleep 20 &&
python ~/cluster_utils/tasklauncher_uni.py @v1g1 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name BiLSTM_eot --visualization_path ../../visualize_html/test --wandb_notes BiLSTM_eot --model_arch bilstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot && sleep 20 &&
python ~/cluster_utils/tasklauncher_uni.py @v1g2 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name GRU_eot --visualization_path ../../visualize_html/test --wandb_notes GRU_eot --model_arch gru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot && sleep 20 &&
python ~/cluster_utils/tasklauncher_uni.py @v1g2 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name LSTM_eot --visualization_path ../../visualize_html/test --wandb_notes LSTM_eot --model_arch lstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot && sleep 20 &&
# LATENT DEPTH
python ~/cluster_utils/tasklauncher_uni.py @v1g3 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name BiGRU_latent --visualization_path ../../visualize_html/test --wandb_notes BiGRU_latent --model_arch bigru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot f_sin f_cos && sleep 20 &&
python ~/cluster_utils/tasklauncher_uni.py @v2g0 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 512  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name BiLSTM_latent --visualization_path ../../visualize_html/test --wandb_notes BiLSTM_latent --model_arch bilstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot f_sin f_cos  && sleep 20 &&
python ~/cluster_utils/tasklauncher_uni.py @v2g1 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name GRU_latent --visualization_path ../../visualize_html/test --wandb_notes GRU_latent --model_arch gru_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot f_sin f_cos  && sleep 20 &&
python ~/cluster_utils/tasklauncher_uni.py @v2g1 python train_ball_trajectory_depth.py --dataset_train_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/train_set --dataset_val_path $DATASET_CLUSTER/Unity/Mixed/NormalScaled/LatentOptimization/val_set --save_checkpoint ../../model_checkpoints/ --batch_size 256  --trajectory_type Mixed --cam_params_file $DATASET_CLUSTER/Unity/Mixed/NormalScaled/No_noise/configFile_camParams_Trial1.json --wandb_tags Results45@29/09/2020  --wandb_name LSTM_latent --visualization_path ../../visualize_html/test --wandb_notes LSTM_latent --model_arch lstm_residual --visualize --clip 5 --noise --lr 0.003 --decay_cycle 70 --wandb_dir ../../ --teacherforcing_mixed --selected_features eot f_sin f_cos
